image:
  file: .gitpod.Dockerfile

tasks:
  - command: cd capstone-backend; mvn package appengine:stage

  - command: cd capstone-frontend; npm install; npm run build

  - command: curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-299.0.0-linux-x86_64.tar.gz; tar zxvf google-cloud-sdk-299.0.0-linux-x86_64.tar.gz google-cloud-sdk; rm -r google-cloud-sdk-299.0.0-linux-x86_64.tar.gz; ./google-cloud-sdk/install.sh; echo -e "To initialize gcloud, Open a new Terminal (Terminal -> New Terminal) and enter 'gcloud init'\n\n"

vscode:
  extensions:
    - dsznajder.es7-react-js-snippets@2.7.1:adU40EmL4YfIciiaLc7LVQ==
