image:
  file: .gitpod.Dockerfile

tasks:
  - init: mvn appengine init
    command: cd capstone-backend; mvn package appengine:stage

  - init: npm run init
    command: cd capstone-frontend; npm install; npm run build